# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 07:02
from __future__ import unicode_literals

import any_imagefield.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import me.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='me.Participant')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'me_participant_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_alive', models.BooleanField(db_index=True, default=False, help_text='Screenshots will be shown if is not alive.')),
                ('is_notable', models.BooleanField(default=False, help_text='Will be shown in CV.')),
                ('has_archive', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField(db_index=True)),
                ('slug', models.SlugField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('image', any_imagefield.models.fields.AnyImageField(blank=True, help_text=b'Save first.', max_length=400, upload_to=me.models.project_images)),
            ],
            options={
                'ordering': ('-date',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explict_title', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('verbose_link', models.CharField(blank=True, max_length=100)),
                ('verbose_link_text', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('client', models.TextField(blank=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='me.Project')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'me_project_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='me.ProjectType')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'me_projecttype_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='me.Role')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'me_role_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', any_imagefield.models.fields.AnyImageField(max_length=400, upload_to=me.models.screenshot_images)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.Project')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=300)),
                ('image', any_imagefield.models.fields.AnyImageField(upload_to=me.models.social_images)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=17, default=0.0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, default=0.0, max_digits=20)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ManyToManyField(blank=True, to='me.ProjectType'),
        ),
        migrations.AddField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.Project'),
        ),
        migrations.AddField(
            model_name='participation',
            name='role',
            field=models.ManyToManyField(to='me.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='roletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='projecttypetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='projecttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='participanttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
