# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=280),
        ),
    ]
