# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_website', models.URLField(blank=True, max_length=100)),
                ('company_alternate_name', models.CharField(blank=True, max_length=50)),
                ('company_alternate_website', models.URLField(blank=True, max_length=100)),
                ('company_location', models.CharField(blank=True, max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('show_only_years', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(help_text=b'')),
            ],
            options={
                'ordering': ('-date_start', '-date_end'),
            },
        ),
    ]
